/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAdminRouteImport } from './routes/app/admin'
import { Route as AppAdminUUserIdRouteImport } from './routes/app/admin.u.$userId'
import { Route as AppChatRouteImport } from './routes/app/chat'
import { Route as AppFeedRouteImport } from './routes/app/feed'
import { Route as AppMessagesRouteImport } from './routes/app/messages'
import { Route as AppPerfsRouteImport } from './routes/app/perfs'
import { Route as AppProfilRouteImport } from './routes/app/profil'
import { Route as AppProgrammeRouteImport } from './routes/app/programme'
import { Route as AppRechercheRouteImport } from './routes/app/recherche'
import { Route as AppSeanceRouteImport } from './routes/app/seance'
import { Route as AppSuiviRouteImport } from './routes/app/suivi'
import { Route as AppUUserIdRouteImport } from './routes/app/u.$userId'
import { Route as AppPerfsExerciseIdRouteImport } from './routes/app/perfs.$exerciseId'
import { Route as AppProgrammeProgramIdRouteImport } from './routes/app/programme.$programId'
import { Route as AppSuiviWorkoutIdRouteImport } from './routes/app/suivi.$workoutId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUUserIdRoute = AppAdminUUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfsRoute = AppPerfsRouteImport.update({
  id: '/perfs',
  path: '/perfs',
  getParentRoute: () => AppRoute,
} as any)
const AppProfilRoute = AppProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AppRoute,
} as any)
const AppProgrammeRoute = AppProgrammeRouteImport.update({
  id: '/programme',
  path: '/programme',
  getParentRoute: () => AppRoute,
} as any)
const AppRechercheRoute = AppRechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => AppRoute,
} as any)
const AppSeanceRoute = AppSeanceRouteImport.update({
  id: '/seance',
  path: '/seance',
  getParentRoute: () => AppRoute,
} as any)
const AppSuiviRoute = AppSuiviRouteImport.update({
  id: '/suivi',
  path: '/suivi',
  getParentRoute: () => AppRoute,
} as any)
const AppUUserIdRoute = AppUUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfsExerciseIdRoute = AppPerfsExerciseIdRouteImport.update({
  id: '/$exerciseId',
  path: '/$exerciseId',
  getParentRoute: () => AppPerfsRoute,
} as any)
const AppProgrammeProgramIdRoute = AppProgrammeProgramIdRouteImport.update({
  id: '/$programId',
  path: '/$programId',
  getParentRoute: () => AppProgrammeRoute,
} as any)
const AppSuiviWorkoutIdRoute = AppSuiviWorkoutIdRouteImport.update({
  id: '/$workoutId',
  path: '/$workoutId',
  getParentRoute: () => AppSuiviRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/admin/u/$userId': typeof AppAdminUUserIdRoute
  '/app/chat': typeof AppChatRoute
  '/app/feed': typeof AppFeedRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/perfs': typeof AppPerfsRouteWithChildren
  '/app/profil': typeof AppProfilRoute
  '/app/programme': typeof AppProgrammeRouteWithChildren
  '/app/recherche': typeof AppRechercheRoute
  '/app/seance': typeof AppSeanceRoute
  '/app/suivi': typeof AppSuiviRouteWithChildren
  '/app/u/$userId': typeof AppUUserIdRoute
  '/app/': typeof AppIndexRoute
  '/app/perfs/$exerciseId': typeof AppPerfsExerciseIdRoute
  '/app/programme/$programId': typeof AppProgrammeProgramIdRoute
  '/app/suivi/$workoutId': typeof AppSuiviWorkoutIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/admin/u/$userId': typeof AppAdminUUserIdRoute
  '/app/chat': typeof AppChatRoute
  '/app/feed': typeof AppFeedRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/perfs': typeof AppPerfsRouteWithChildren
  '/app/profil': typeof AppProfilRoute
  '/app/programme': typeof AppProgrammeRouteWithChildren
  '/app/recherche': typeof AppRechercheRoute
  '/app/seance': typeof AppSeanceRoute
  '/app/suivi': typeof AppSuiviRouteWithChildren
  '/app/u/$userId': typeof AppUUserIdRoute
  '/app': typeof AppIndexRoute
  '/app/perfs/$exerciseId': typeof AppPerfsExerciseIdRoute
  '/app/programme/$programId': typeof AppProgrammeProgramIdRoute
  '/app/suivi/$workoutId': typeof AppSuiviWorkoutIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/admin/u/$userId': typeof AppAdminUUserIdRoute
  '/app/chat': typeof AppChatRoute
  '/app/feed': typeof AppFeedRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/perfs': typeof AppPerfsRouteWithChildren
  '/app/profil': typeof AppProfilRoute
  '/app/programme': typeof AppProgrammeRouteWithChildren
  '/app/recherche': typeof AppRechercheRoute
  '/app/seance': typeof AppSeanceRoute
  '/app/suivi': typeof AppSuiviRouteWithChildren
  '/app/u/$userId': typeof AppUUserIdRoute
  '/app/': typeof AppIndexRoute
  '/app/perfs/$exerciseId': typeof AppPerfsExerciseIdRoute
  '/app/programme/$programId': typeof AppProgrammeProgramIdRoute
  '/app/suivi/$workoutId': typeof AppSuiviWorkoutIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/connexion'
    | '/app/admin'
    | '/app/admin/u/$userId'
    | '/app/chat'
    | '/app/feed'
    | '/app/messages'
    | '/app/perfs'
    | '/app/profil'
    | '/app/programme'
    | '/app/recherche'
    | '/app/seance'
    | '/app/suivi'
    | '/app/u/$userId'
    | '/app/'
    | '/app/perfs/$exerciseId'
    | '/app/programme/$programId'
    | '/app/suivi/$workoutId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connexion'
    | '/app/admin'
    | '/app/admin/u/$userId'
    | '/app/chat'
    | '/app/feed'
    | '/app/messages'
    | '/app/perfs'
    | '/app/profil'
    | '/app/programme'
    | '/app/recherche'
    | '/app/seance'
    | '/app/suivi'
    | '/app/u/$userId'
    | '/app'
    | '/app/perfs/$exerciseId'
    | '/app/programme/$programId'
    | '/app/suivi/$workoutId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/connexion'
    | '/app/admin'
    | '/app/admin/u/$userId'
    | '/app/chat'
    | '/app/feed'
    | '/app/messages'
    | '/app/perfs'
    | '/app/profil'
    | '/app/programme'
    | '/app/recherche'
    | '/app/seance'
    | '/app/suivi'
    | '/app/u/$userId'
    | '/app/'
    | '/app/perfs/$exerciseId'
    | '/app/programme/$programId'
    | '/app/suivi/$workoutId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ConnexionRoute: typeof ConnexionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/u/$userId': {
      id: '/app/admin/u/$userId'
      path: '/u/$userId'
      fullPath: '/app/admin/u/$userId'
      preLoaderRoute: typeof AppAdminUUserIdRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/feed': {
      id: '/app/feed'
      path: '/feed'
      fullPath: '/app/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfs': {
      id: '/app/perfs'
      path: '/perfs'
      fullPath: '/app/perfs'
      preLoaderRoute: typeof AppPerfsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profil': {
      id: '/app/profil'
      path: '/profil'
      fullPath: '/app/profil'
      preLoaderRoute: typeof AppProfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/programme': {
      id: '/app/programme'
      path: '/programme'
      fullPath: '/app/programme'
      preLoaderRoute: typeof AppProgrammeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recherche': {
      id: '/app/recherche'
      path: '/recherche'
      fullPath: '/app/recherche'
      preLoaderRoute: typeof AppRechercheRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/seance': {
      id: '/app/seance'
      path: '/seance'
      fullPath: '/app/seance'
      preLoaderRoute: typeof AppSeanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suivi': {
      id: '/app/suivi'
      path: '/suivi'
      fullPath: '/app/suivi'
      preLoaderRoute: typeof AppSuiviRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/u/$userId': {
      id: '/app/u/$userId'
      path: '/u/$userId'
      fullPath: '/app/u/$userId'
      preLoaderRoute: typeof AppUUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfs/$exerciseId': {
      id: '/app/perfs/$exerciseId'
      path: '/$exerciseId'
      fullPath: '/app/perfs/$exerciseId'
      preLoaderRoute: typeof AppPerfsExerciseIdRouteImport
      parentRoute: typeof AppPerfsRoute
    }
    '/app/programme/$programId': {
      id: '/app/programme/$programId'
      path: '/$programId'
      fullPath: '/app/programme/$programId'
      preLoaderRoute: typeof AppProgrammeProgramIdRouteImport
      parentRoute: typeof AppProgrammeRoute
    }
    '/app/suivi/$workoutId': {
      id: '/app/suivi/$workoutId'
      path: '/$workoutId'
      fullPath: '/app/suivi/$workoutId'
      preLoaderRoute: typeof AppSuiviWorkoutIdRouteImport
      parentRoute: typeof AppSuiviRoute
    }
  }
}

interface AppPerfsRouteChildren {
  AppPerfsExerciseIdRoute: typeof AppPerfsExerciseIdRoute
}

const AppPerfsRouteChildren: AppPerfsRouteChildren = {
  AppPerfsExerciseIdRoute: AppPerfsExerciseIdRoute,
}

const AppPerfsRouteWithChildren = AppPerfsRoute._addFileChildren(
  AppPerfsRouteChildren,
)

interface AppProgrammeRouteChildren {
  AppProgrammeProgramIdRoute: typeof AppProgrammeProgramIdRoute
}

const AppProgrammeRouteChildren: AppProgrammeRouteChildren = {
  AppProgrammeProgramIdRoute: AppProgrammeProgramIdRoute,
}

const AppProgrammeRouteWithChildren = AppProgrammeRoute._addFileChildren(
  AppProgrammeRouteChildren,
)

interface AppSuiviRouteChildren {
  AppSuiviWorkoutIdRoute: typeof AppSuiviWorkoutIdRoute
}

const AppSuiviRouteChildren: AppSuiviRouteChildren = {
  AppSuiviWorkoutIdRoute: AppSuiviWorkoutIdRoute,
}

const AppSuiviRouteWithChildren = AppSuiviRoute._addFileChildren(
  AppSuiviRouteChildren,
)

interface AppAdminRouteChildren {
  AppAdminUUserIdRoute: typeof AppAdminUUserIdRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminUUserIdRoute: AppAdminUUserIdRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppChatRoute: typeof AppChatRoute
  AppFeedRoute: typeof AppFeedRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppPerfsRoute: typeof AppPerfsRouteWithChildren
  AppProfilRoute: typeof AppProfilRoute
  AppProgrammeRoute: typeof AppProgrammeRouteWithChildren
  AppRechercheRoute: typeof AppRechercheRoute
  AppSeanceRoute: typeof AppSeanceRoute
  AppSuiviRoute: typeof AppSuiviRouteWithChildren
  AppUUserIdRoute: typeof AppUUserIdRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppChatRoute: AppChatRoute,
  AppFeedRoute: AppFeedRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppPerfsRoute: AppPerfsRouteWithChildren,
  AppProfilRoute: AppProfilRoute,
  AppProgrammeRoute: AppProgrammeRouteWithChildren,
  AppRechercheRoute: AppRechercheRoute,
  AppSeanceRoute: AppSeanceRoute,
  AppSuiviRoute: AppSuiviRouteWithChildren,
  AppUUserIdRoute: AppUUserIdRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ConnexionRoute: ConnexionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
